/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controladores.ControladorUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TelaLogin extends javax.swing.JFrame {
    ControladorUsuarios controladorUsuarios;
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin(ControladorUsuarios controladorUsuarios) {
        initComponents();
        this.controladorUsuarios = controladorUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        frase = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoLogin = new javax.swing.JFormattedTextField();
        botaoSair = new javax.swing.JButton();
        botaoLogin = new javax.swing.JButton();
        botaoNovoCadastro = new javax.swing.JButton();
        botaoAtualizarTaxas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(1366, 1366, 1366, 1366));
        setMaximumSize(new java.awt.Dimension(1366, 1366));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.setFocusCycleRoot(true);
        jPanel2.setFocusTraversalPolicy(null);
        jPanel2.setFocusable(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel2.setText("Login:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 100, 54, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 129, 54, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/logos/logo.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 13, 134, 180));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Coin Value");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 13, 266, 41));

        frase.setBackground(new java.awt.Color(255, 255, 255));
        frase.setFont(new java.awt.Font("Perpetua", 2, 16)); // NOI18N
        frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frase.setText("Sua Carteira Virtual");
        jPanel2.add(frase, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 61, 266, 31));

        campoSenha.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 128, 207, -1));

        campoLogin.setBackground(new java.awt.Color(244, 244, 244));
        try {
            campoLogin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(campoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 99, 207, -1));

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        jPanel2.add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 163, 95, 30));

        botaoLogin.setText("Login");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 163, 95, 30));

        botaoNovoCadastro.setText("Usuários");
        botaoNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoCadastroActionPerformed(evt);
            }
        });
        jPanel2.add(botaoNovoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 200, 198, 35));

        botaoAtualizarTaxas.setText("Alterar Taxas");
        botaoAtualizarTaxas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarTaxasActionPerformed(evt);
            }
        });
        jPanel2.add(botaoAtualizarTaxas, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 200, 207, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
       // Armazena os valores lidos do formulário em variáveis
        String login = campoLogin.getText();
        String senha = String.valueOf(campoSenha.getPassword());

        boolean autenticao = controladorUsuarios.autenticarUsuario(login, senha);
        
        if(autenticao){
            controladorUsuarios.pedirTelaCarteira(login);
        }else{
            JOptionPane.showMessageDialog(null, "Login e/ou Senha invalido(s)!");
        }
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void botaoAtualizarTaxasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarTaxasActionPerformed
        controladorUsuarios.pedirTelaTaxas();
    }//GEN-LAST:event_botaoAtualizarTaxasActionPerformed

    private void botaoNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoCadastroActionPerformed
        controladorUsuarios.exibirTelaCadastro();
    }//GEN-LAST:event_botaoNovoCadastroActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarTaxas;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton botaoNovoCadastro;
    private javax.swing.JButton botaoSair;
    private javax.swing.JFormattedTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel frase;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
